[build]
  command = "npm run build"
  publish = "dist"

# Disable Netlify's built-in prerendering (handled by Supabase Edge Function)
[context.production]
  [context.production.processing]
    skip_processing = false
  [context.production.build]
    command = "npm run build"
    environment = { NETLIFY_PRERENDER = "false" }

# Bot-specific routing: redirect bots to seo-prerender function
[[redirects]]
  from = "/*"
  to = "https://fhqwacmokbtbspkxjixf.supabase.co/functions/v1/seo-prerender?domain=:host&path=:splat"
  status = 200
  conditions = {User-Agent = ["*bot*", "*crawler*", "*spider*", "*Googlebot*", "*Bingbot*", "*facebookexternalhit*", "*Twitterbot*", "*LinkedInBot*", "*WhatsApp*", "*Telegram*", "facebookexternalhit/1.1", "facebookcatalog/*", "Facebot", "*FacebookBot*", "*facebookcatalog*", "*FacebookExternalHit*"]}
  
# Force HTTPS and add debug headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Pass-through for static assets (JS, CSS, images, etc.)
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico" 
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

# Serve SPA for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"