[build]
  command = "npm run build"
  publish = "dist"

# Enable Netlify's built-in prerendering for SEO
[context.production]
  [context.production.processing]
    skip_processing = false
  [context.production.build]
    command = "npm run build"
    environment = { NETLIFY_PRERENDER = "true" }

# Webhook redirects
[[redirects]]
  from = "/steadfast-webhook"
  to = "https://fhqwacmokbtbspkxjixf.functions.supabase.co/steadfast-webhook"
  status = 200

# Static assets bypass (keep SPA loading fast)
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/*.js"
  to = "/:splat.js"
  status = 200

[[redirects]]
  from = "/*.css"
  to = "/:splat.css"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

# Serve HTML snapshots for all other routes
[[redirects]]
  from = "/*"
  to = "https://fhqwacmokbtbspkxjixf.functions.supabase.co/serve-html?domain=:host&path=/:splat"
  status = 200

# Cache control for SEO prerender responses
[[headers]]
  for = "/__bot/*"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=3600"
    Content-Type = "text/html; charset=UTF-8"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"