[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[edge_functions]]
  function = "server-render"
  path = "/*"

[context.production]
  [context.production.edge_functions]
    server-render = "/*"
