[build]
  command = "npm run build"
  publish = "dist"

# Enable Netlify Prerender for better SEO
[context.production]
  [context.production.processing]
    skip_processing = false
  [context.production.build]
    command = "npm run build"
    environment = { NETLIFY_PRERENDER = "true" }

# Prerender specific routes for SEO
[[plugins]]
  package = "@netlify/plugin-prerender-spa"
  [plugins.inputs]
    # Prerender routes that match storefront patterns
    routes = [
      "/w/*",
      "/f/*", 
      "/storefront/*"
    ]
    # Don't prerender dashboard routes
    exclude = [
      "/dashboard/*",
      "/admin/*",
      "/auth/*"
    ]

# Redirect rules for domain-based routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"