[build]
  command = "npm run build"
  publish = "dist"

# Enable Netlify's built-in prerendering for SEO
[context.production]
  [context.production.processing]
    skip_processing = false
  [context.production.build]
    command = "npm run build"
    environment = { NETLIFY_PRERENDER = "true" }

# Webhook redirects
[[redirects]]
  from = "/steadfast-webhook"
  to = "https://fhqwacmokbtbspkxjixf.functions.supabase.co/steadfast-webhook"
  status = 200

# Route website and funnel pages through our serve-page function
[[redirects]]
  from = "/site/*"
  to = "https://fhqwacmokbtbspkxjixf.functions.supabase.co/serve-page?prefix=site&splat=:splat"
  status = 200
  force = true

[[redirects]]
  from = "/website/*"
  to = "https://fhqwacmokbtbspkxjixf.functions.supabase.co/serve-page?prefix=website&splat=:splat"
  status = 200
  force = true

[[redirects]]
  from = "/funnel/*"
  to = "https://fhqwacmokbtbspkxjixf.functions.supabase.co/serve-page?prefix=funnel&splat=:splat"
  status = 200
  force = true

# Custom domain routing - route all custom domain traffic through serve-page
[[redirects]]
  from = "/*"
  to = "https://fhqwacmokbtbspkxjixf.functions.supabase.co/serve-page?domain=:host&path=:splat"
  status = 200
  force = true
  conditions = {Host = "!ecombuildr.com,!*.netlify.app"}

# Serve SPA for all other routes (app, admin, etc.)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache control for SEO prerender responses
[[headers]]
  for = "/__bot/*"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=3600"
    Content-Type = "text/html; charset=UTF-8"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"