name = "ecombuildr"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "./dist"

# Environment variables for Pages Functions
[vars]
NODE_ENV = "production"
SUPABASE_URL = "https://fhqwacmokbtbspkxjixf.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZocXdhY21va2J0YnNwa3hqaXhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MjYyMzUsImV4cCI6MjA2OTIwMjIzNX0.BaqDCDcynSahyDxEUIyZLLtyXpd959y5Tv6t6tIF3GM"
