name = "ecombuildr"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "./dist"

[[pages_build_output.compatibility_flags]]
nodejs_compat = true

# Environment variables for Pages Functions
[vars]
NODE_ENV = "production"

# KV namespace for caching (optional but recommended for SEO data)
# [[kv_namespaces]]
# binding = "SEO_CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"
